// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rpc.proto

#include "rpc.pb.h"
#include "rpc.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace calculate {

static const char* Calculate_method_names[] = {
  "/calculate.Calculate/Add",
};

std::unique_ptr< Calculate::Stub> Calculate::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Calculate::Stub> stub(new Calculate::Stub(channel, options));
  return stub;
}

Calculate::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Add_(Calculate_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Calculate::Stub::Add(::grpc::ClientContext* context, const ::calculate::AddRequest& request, ::calculate::AddResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::calculate::AddRequest, ::calculate::AddResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Add_, context, request, response);
}

void Calculate::Stub::async::Add(::grpc::ClientContext* context, const ::calculate::AddRequest* request, ::calculate::AddResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::calculate::AddRequest, ::calculate::AddResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Add_, context, request, response, std::move(f));
}

void Calculate::Stub::async::Add(::grpc::ClientContext* context, const ::calculate::AddRequest* request, ::calculate::AddResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Add_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::calculate::AddResponse>* Calculate::Stub::PrepareAsyncAddRaw(::grpc::ClientContext* context, const ::calculate::AddRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::calculate::AddResponse, ::calculate::AddRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Add_, context, request);
}

::grpc::ClientAsyncResponseReader< ::calculate::AddResponse>* Calculate::Stub::AsyncAddRaw(::grpc::ClientContext* context, const ::calculate::AddRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddRaw(context, request, cq);
  result->StartCall();
  return result;
}

Calculate::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Calculate_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Calculate::Service, ::calculate::AddRequest, ::calculate::AddResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Calculate::Service* service,
             ::grpc::ServerContext* ctx,
             const ::calculate::AddRequest* req,
             ::calculate::AddResponse* resp) {
               return service->Add(ctx, req, resp);
             }, this)));
}

Calculate::Service::~Service() {
}

::grpc::Status Calculate::Service::Add(::grpc::ServerContext* context, const ::calculate::AddRequest* request, ::calculate::AddResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace calculate

