// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_person_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_person_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_person_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_person_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_person_2eproto;
namespace person {
class Contact;
struct ContactDefaultTypeInternal;
extern ContactDefaultTypeInternal _Contact_default_instance_;
class Student;
struct StudentDefaultTypeInternal;
extern StudentDefaultTypeInternal _Student_default_instance_;
class Student_ScoreEntry_DoNotUse;
struct Student_ScoreEntry_DoNotUseDefaultTypeInternal;
extern Student_ScoreEntry_DoNotUseDefaultTypeInternal _Student_ScoreEntry_DoNotUse_default_instance_;
}  // namespace person
PROTOBUF_NAMESPACE_OPEN
template<> ::person::Contact* Arena::CreateMaybeMessage<::person::Contact>(Arena*);
template<> ::person::Student* Arena::CreateMaybeMessage<::person::Student>(Arena*);
template<> ::person::Student_ScoreEntry_DoNotUse* Arena::CreateMaybeMessage<::person::Student_ScoreEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace person {

enum StuType : int {
  NORMAL = 0,
  CADRE = 2,
  StuType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  StuType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool StuType_IsValid(int value);
constexpr StuType StuType_MIN = NORMAL;
constexpr StuType StuType_MAX = CADRE;
constexpr int StuType_ARRAYSIZE = StuType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* StuType_descriptor();
template<typename T>
inline const std::string& StuType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, StuType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function StuType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    StuType_descriptor(), enum_t_value);
}
inline bool StuType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, StuType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<StuType>(
    StuType_descriptor(), name, value);
}
// ===================================================================

class Student_ScoreEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Student_ScoreEntry_DoNotUse, 
    std::string, float,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Student_ScoreEntry_DoNotUse, 
    std::string, float,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT> SuperType;
  Student_ScoreEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR Student_ScoreEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit Student_ScoreEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const Student_ScoreEntry_DoNotUse& other);
  static const Student_ScoreEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Student_ScoreEntry_DoNotUse*>(&_Student_ScoreEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "person.Student.ScoreEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_person_2eproto;
};

// -------------------------------------------------------------------

class Student final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:person.Student) */ {
 public:
  inline Student() : Student(nullptr) {}
  ~Student() override;
  explicit PROTOBUF_CONSTEXPR Student(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Student(const Student& from);
  Student(Student&& from) noexcept
    : Student() {
    *this = ::std::move(from);
  }

  inline Student& operator=(const Student& from) {
    CopyFrom(from);
    return *this;
  }
  inline Student& operator=(Student&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Student& default_instance() {
    return *internal_default_instance();
  }
  enum TestOneofCase {
    kWeight = 6,
    kHeight = 7,
    TEST_ONEOF_NOT_SET = 0,
  };

  static inline const Student* internal_default_instance() {
    return reinterpret_cast<const Student*>(
               &_Student_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Student& a, Student& b) {
    a.Swap(&b);
  }
  inline void Swap(Student* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Student* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Student* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Student>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Student& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Student& from) {
    Student::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Student* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "person.Student";
  }
  protected:
  explicit Student(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kHobbyFieldNumber = 3,
    kScoreFieldNumber = 4,
    kNameFieldNumber = 2,
    kBirthFieldNumber = 8,
    kSnFieldNumber = 1,
    kTypeFieldNumber = 5,
    kWeightFieldNumber = 6,
    kHeightFieldNumber = 7,
  };
  // repeated string hobby = 3;
  int hobby_size() const;
  private:
  int _internal_hobby_size() const;
  public:
  void clear_hobby();
  const std::string& hobby(int index) const;
  std::string* mutable_hobby(int index);
  void set_hobby(int index, const std::string& value);
  void set_hobby(int index, std::string&& value);
  void set_hobby(int index, const char* value);
  void set_hobby(int index, const char* value, size_t size);
  std::string* add_hobby();
  void add_hobby(const std::string& value);
  void add_hobby(std::string&& value);
  void add_hobby(const char* value);
  void add_hobby(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& hobby() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_hobby();
  private:
  const std::string& _internal_hobby(int index) const;
  std::string* _internal_add_hobby();
  public:

  // map<string, float> score = 4;
  int score_size() const;
  private:
  int _internal_score_size() const;
  public:
  void clear_score();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >&
      _internal_score() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >*
      _internal_mutable_score();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >&
      score() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >*
      mutable_score();

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // optional string birth = 8;
  bool has_birth() const;
  private:
  bool _internal_has_birth() const;
  public:
  void clear_birth();
  const std::string& birth() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_birth(ArgT0&& arg0, ArgT... args);
  std::string* mutable_birth();
  PROTOBUF_NODISCARD std::string* release_birth();
  void set_allocated_birth(std::string* birth);
  private:
  const std::string& _internal_birth() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_birth(const std::string& value);
  std::string* _internal_mutable_birth();
  public:

  // int32 sn = 1;
  void clear_sn();
  int32_t sn() const;
  void set_sn(int32_t value);
  private:
  int32_t _internal_sn() const;
  void _internal_set_sn(int32_t value);
  public:

  // .person.StuType type = 5;
  void clear_type();
  ::person::StuType type() const;
  void set_type(::person::StuType value);
  private:
  ::person::StuType _internal_type() const;
  void _internal_set_type(::person::StuType value);
  public:

  // int32 weight = 6;
  bool has_weight() const;
  private:
  bool _internal_has_weight() const;
  public:
  void clear_weight();
  int32_t weight() const;
  void set_weight(int32_t value);
  private:
  int32_t _internal_weight() const;
  void _internal_set_weight(int32_t value);
  public:

  // int32 height = 7;
  bool has_height() const;
  private:
  bool _internal_has_height() const;
  public:
  void clear_height();
  int32_t height() const;
  void set_height(int32_t value);
  private:
  int32_t _internal_height() const;
  void _internal_set_height(int32_t value);
  public:

  void clear_test_oneof();
  TestOneofCase test_oneof_case() const;
  // @@protoc_insertion_point(class_scope:person.Student)
 private:
  class _Internal;
  void set_has_weight();
  void set_has_height();

  inline bool has_test_oneof() const;
  inline void clear_has_test_oneof();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> hobby_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        Student_ScoreEntry_DoNotUse,
        std::string, float,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT> score_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr birth_;
    int32_t sn_;
    int type_;
    union TestOneofUnion {
      constexpr TestOneofUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      int32_t weight_;
      int32_t height_;
    } test_oneof_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_person_2eproto;
};
// -------------------------------------------------------------------

class Contact final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:person.Contact) */ {
 public:
  inline Contact() : Contact(nullptr) {}
  ~Contact() override;
  explicit PROTOBUF_CONSTEXPR Contact(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Contact(const Contact& from);
  Contact(Contact&& from) noexcept
    : Contact() {
    *this = ::std::move(from);
  }

  inline Contact& operator=(const Contact& from) {
    CopyFrom(from);
    return *this;
  }
  inline Contact& operator=(Contact&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Contact& default_instance() {
    return *internal_default_instance();
  }
  static inline const Contact* internal_default_instance() {
    return reinterpret_cast<const Contact*>(
               &_Contact_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Contact& a, Contact& b) {
    a.Swap(&b);
  }
  inline void Swap(Contact* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Contact* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Contact* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Contact>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Contact& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Contact& from) {
    Contact::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Contact* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "person.Contact";
  }
  protected:
  explicit Contact(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStudentsFieldNumber = 1,
  };
  // repeated .person.Student students = 1;
  int students_size() const;
  private:
  int _internal_students_size() const;
  public:
  void clear_students();
  ::person::Student* mutable_students(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::person::Student >*
      mutable_students();
  private:
  const ::person::Student& _internal_students(int index) const;
  ::person::Student* _internal_add_students();
  public:
  const ::person::Student& students(int index) const;
  ::person::Student* add_students();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::person::Student >&
      students() const;

  // @@protoc_insertion_point(class_scope:person.Contact)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::person::Student > students_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_person_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Student

// int32 sn = 1;
inline void Student::clear_sn() {
  _impl_.sn_ = 0;
}
inline int32_t Student::_internal_sn() const {
  return _impl_.sn_;
}
inline int32_t Student::sn() const {
  // @@protoc_insertion_point(field_get:person.Student.sn)
  return _internal_sn();
}
inline void Student::_internal_set_sn(int32_t value) {
  
  _impl_.sn_ = value;
}
inline void Student::set_sn(int32_t value) {
  _internal_set_sn(value);
  // @@protoc_insertion_point(field_set:person.Student.sn)
}

// string name = 2;
inline void Student::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Student::name() const {
  // @@protoc_insertion_point(field_get:person.Student.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Student::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:person.Student.name)
}
inline std::string* Student::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:person.Student.name)
  return _s;
}
inline const std::string& Student::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Student::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Student::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Student::release_name() {
  // @@protoc_insertion_point(field_release:person.Student.name)
  return _impl_.name_.Release();
}
inline void Student::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:person.Student.name)
}

// repeated string hobby = 3;
inline int Student::_internal_hobby_size() const {
  return _impl_.hobby_.size();
}
inline int Student::hobby_size() const {
  return _internal_hobby_size();
}
inline void Student::clear_hobby() {
  _impl_.hobby_.Clear();
}
inline std::string* Student::add_hobby() {
  std::string* _s = _internal_add_hobby();
  // @@protoc_insertion_point(field_add_mutable:person.Student.hobby)
  return _s;
}
inline const std::string& Student::_internal_hobby(int index) const {
  return _impl_.hobby_.Get(index);
}
inline const std::string& Student::hobby(int index) const {
  // @@protoc_insertion_point(field_get:person.Student.hobby)
  return _internal_hobby(index);
}
inline std::string* Student::mutable_hobby(int index) {
  // @@protoc_insertion_point(field_mutable:person.Student.hobby)
  return _impl_.hobby_.Mutable(index);
}
inline void Student::set_hobby(int index, const std::string& value) {
  _impl_.hobby_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:person.Student.hobby)
}
inline void Student::set_hobby(int index, std::string&& value) {
  _impl_.hobby_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:person.Student.hobby)
}
inline void Student::set_hobby(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.hobby_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:person.Student.hobby)
}
inline void Student::set_hobby(int index, const char* value, size_t size) {
  _impl_.hobby_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:person.Student.hobby)
}
inline std::string* Student::_internal_add_hobby() {
  return _impl_.hobby_.Add();
}
inline void Student::add_hobby(const std::string& value) {
  _impl_.hobby_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:person.Student.hobby)
}
inline void Student::add_hobby(std::string&& value) {
  _impl_.hobby_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:person.Student.hobby)
}
inline void Student::add_hobby(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.hobby_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:person.Student.hobby)
}
inline void Student::add_hobby(const char* value, size_t size) {
  _impl_.hobby_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:person.Student.hobby)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Student::hobby() const {
  // @@protoc_insertion_point(field_list:person.Student.hobby)
  return _impl_.hobby_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Student::mutable_hobby() {
  // @@protoc_insertion_point(field_mutable_list:person.Student.hobby)
  return &_impl_.hobby_;
}

// map<string, float> score = 4;
inline int Student::_internal_score_size() const {
  return _impl_.score_.size();
}
inline int Student::score_size() const {
  return _internal_score_size();
}
inline void Student::clear_score() {
  _impl_.score_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >&
Student::_internal_score() const {
  return _impl_.score_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >&
Student::score() const {
  // @@protoc_insertion_point(field_map:person.Student.score)
  return _internal_score();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >*
Student::_internal_mutable_score() {
  return _impl_.score_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, float >*
Student::mutable_score() {
  // @@protoc_insertion_point(field_mutable_map:person.Student.score)
  return _internal_mutable_score();
}

// .person.StuType type = 5;
inline void Student::clear_type() {
  _impl_.type_ = 0;
}
inline ::person::StuType Student::_internal_type() const {
  return static_cast< ::person::StuType >(_impl_.type_);
}
inline ::person::StuType Student::type() const {
  // @@protoc_insertion_point(field_get:person.Student.type)
  return _internal_type();
}
inline void Student::_internal_set_type(::person::StuType value) {
  
  _impl_.type_ = value;
}
inline void Student::set_type(::person::StuType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:person.Student.type)
}

// int32 weight = 6;
inline bool Student::_internal_has_weight() const {
  return test_oneof_case() == kWeight;
}
inline bool Student::has_weight() const {
  return _internal_has_weight();
}
inline void Student::set_has_weight() {
  _impl_._oneof_case_[0] = kWeight;
}
inline void Student::clear_weight() {
  if (_internal_has_weight()) {
    _impl_.test_oneof_.weight_ = 0;
    clear_has_test_oneof();
  }
}
inline int32_t Student::_internal_weight() const {
  if (_internal_has_weight()) {
    return _impl_.test_oneof_.weight_;
  }
  return 0;
}
inline void Student::_internal_set_weight(int32_t value) {
  if (!_internal_has_weight()) {
    clear_test_oneof();
    set_has_weight();
  }
  _impl_.test_oneof_.weight_ = value;
}
inline int32_t Student::weight() const {
  // @@protoc_insertion_point(field_get:person.Student.weight)
  return _internal_weight();
}
inline void Student::set_weight(int32_t value) {
  _internal_set_weight(value);
  // @@protoc_insertion_point(field_set:person.Student.weight)
}

// int32 height = 7;
inline bool Student::_internal_has_height() const {
  return test_oneof_case() == kHeight;
}
inline bool Student::has_height() const {
  return _internal_has_height();
}
inline void Student::set_has_height() {
  _impl_._oneof_case_[0] = kHeight;
}
inline void Student::clear_height() {
  if (_internal_has_height()) {
    _impl_.test_oneof_.height_ = 0;
    clear_has_test_oneof();
  }
}
inline int32_t Student::_internal_height() const {
  if (_internal_has_height()) {
    return _impl_.test_oneof_.height_;
  }
  return 0;
}
inline void Student::_internal_set_height(int32_t value) {
  if (!_internal_has_height()) {
    clear_test_oneof();
    set_has_height();
  }
  _impl_.test_oneof_.height_ = value;
}
inline int32_t Student::height() const {
  // @@protoc_insertion_point(field_get:person.Student.height)
  return _internal_height();
}
inline void Student::set_height(int32_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:person.Student.height)
}

// optional string birth = 8;
inline bool Student::_internal_has_birth() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Student::has_birth() const {
  return _internal_has_birth();
}
inline void Student::clear_birth() {
  _impl_.birth_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Student::birth() const {
  // @@protoc_insertion_point(field_get:person.Student.birth)
  return _internal_birth();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Student::set_birth(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.birth_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:person.Student.birth)
}
inline std::string* Student::mutable_birth() {
  std::string* _s = _internal_mutable_birth();
  // @@protoc_insertion_point(field_mutable:person.Student.birth)
  return _s;
}
inline const std::string& Student::_internal_birth() const {
  return _impl_.birth_.Get();
}
inline void Student::_internal_set_birth(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.birth_.Set(value, GetArenaForAllocation());
}
inline std::string* Student::_internal_mutable_birth() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.birth_.Mutable(GetArenaForAllocation());
}
inline std::string* Student::release_birth() {
  // @@protoc_insertion_point(field_release:person.Student.birth)
  if (!_internal_has_birth()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.birth_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.birth_.IsDefault()) {
    _impl_.birth_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Student::set_allocated_birth(std::string* birth) {
  if (birth != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.birth_.SetAllocated(birth, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.birth_.IsDefault()) {
    _impl_.birth_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:person.Student.birth)
}

inline bool Student::has_test_oneof() const {
  return test_oneof_case() != TEST_ONEOF_NOT_SET;
}
inline void Student::clear_has_test_oneof() {
  _impl_._oneof_case_[0] = TEST_ONEOF_NOT_SET;
}
inline Student::TestOneofCase Student::test_oneof_case() const {
  return Student::TestOneofCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// Contact

// repeated .person.Student students = 1;
inline int Contact::_internal_students_size() const {
  return _impl_.students_.size();
}
inline int Contact::students_size() const {
  return _internal_students_size();
}
inline void Contact::clear_students() {
  _impl_.students_.Clear();
}
inline ::person::Student* Contact::mutable_students(int index) {
  // @@protoc_insertion_point(field_mutable:person.Contact.students)
  return _impl_.students_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::person::Student >*
Contact::mutable_students() {
  // @@protoc_insertion_point(field_mutable_list:person.Contact.students)
  return &_impl_.students_;
}
inline const ::person::Student& Contact::_internal_students(int index) const {
  return _impl_.students_.Get(index);
}
inline const ::person::Student& Contact::students(int index) const {
  // @@protoc_insertion_point(field_get:person.Contact.students)
  return _internal_students(index);
}
inline ::person::Student* Contact::_internal_add_students() {
  return _impl_.students_.Add();
}
inline ::person::Student* Contact::add_students() {
  ::person::Student* _add = _internal_add_students();
  // @@protoc_insertion_point(field_add:person.Contact.students)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::person::Student >&
Contact::students() const {
  // @@protoc_insertion_point(field_list:person.Contact.students)
  return _impl_.students_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace person

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::person::StuType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::person::StuType>() {
  return ::person::StuType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_person_2eproto
